### ISSUE TITLE
Incorrect Supported Hardware for macOS Sonoma 

### ISSUE THREAD

**Issue by sjbarkey** [MLBZ521/MacAdmin#27]
macOS Sonoma dropped support for MacBook (Retina, 12-inch, 2017) (MacBook10,1), but the Extension Attribute is still identifying the device as "Sonoma*"

**Comment by MLBZ521** [comment]
Ah, the reverse RegEx logic I have going on sometime trips me up.

Fixed in 47168a9.

Thanks for reporting this @sjbarkey!

**Comment by sjbarkey** [comment]
@MLBZ521 Unfortunately, I'm still seeing the same thing with 2.5.4 where "MacBook10,1" is still returning "Sonoma*" when it should be returning "Ventura*".

I've checked with both an EA and locally on one of the devices.

**Comment by MLBZ521** [comment]
@sjbarkey Ah, I think I looked at the wrong line in my testing and got the result confused with something else.  Also, again, the reverse RegEx logic tripped me up -- I originally had it correct, I just forgot that Bash doesn't understand `\d`, so while the RegEx was correct, it wasn't valid for the Bash interpreter.

Fixed in v2.5.5 6a8336d.

**Comment by sjbarkey** [comment]
RegEx always makes my brain hurt.  Thank you for the quick attention.

Local tests and Jamf EA appear to be reporting "Ventura*" correctly now!
